cloud:
  aws:
    s3:
      credentials:
        accessKey: ${AWS_S3_ACCESSKEY}
        secretKey: ${AWS_S3_SECRETKEY}
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false